import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "JSON Swiss - Professional JSON Editor, Validator & Converter | Online JSON Tools",
  description: "Professional JSON toolkit with formatting, validation, conversion, and code generation. Features AI-powered repair, tree/table views, search, and support for 12+ programming languages. Free online JSON editor.",
  keywords: [
    "json editor",
    "json validator", 
    "json formatter",
    "json converter",
    "json to csv",
    "json to xml", 
    "json to yaml",
    "json repair",
    "json tools",
    "online json editor",
    "json viewer",
    "json prettifier",
    "json minifier",
    "json schema",
    "json compare",
    "json diff",
    "code generator",
    "programming tools",
    "web development",
    "api tools"
  ],
  authors: [{ name: "JSON Swiss Team" }],
  creator: "JSON Swiss",
  publisher: "JSON Swiss",
  category: "Web Development Tools",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://jsonswiss.com",
    siteName: "JSON Swiss",
    title: "JSON Swiss - Professional JSON Editor & Converter",
    description: "Complete JSON toolkit with formatting, validation, conversion, and AI-powered repair. Support for CSV, XML, YAML and 12+ programming languages.",
    images: [
      {
        url: "https://jsonswiss.com/og-image.png",
        width: 1200,
        height: 630,
        alt: "JSON Swiss - Professional JSON Editor and Validator",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@jsonswiss",
    creator: "@jsonswiss", 
    title: "JSON Swiss - Professional JSON Tools",
    description: "Complete JSON toolkit with formatting, validation, conversion, and AI-powered repair. Free online JSON editor.",
    images: ["https://jsonswiss.com/twitter-card.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: "https://jsonswiss.com",
  },
  verification: {
    google: "your-google-site-verification-code",
    yandex: "your-yandex-verification-code",
    yahoo: "your-yahoo-verification-code",
  },
  other: {
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "default",
    "apple-mobile-web-app-title": "JSON Swiss",
    "mobile-web-app-capable": "yes",
    "msapplication-TileColor": "#2563eb",
    "theme-color": "#2563eb",
  },
};